name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - github-pages
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "v18.10"

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build --prod --output-path=dist/musayi-miyamato-quotes

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/musayi-miyamato-quotes

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: dist/musayi-miyamato-quotes

      - name: Create .nojekyll file
        run: echo "" > dist/musayi-miyamato-quotes/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/musayi-miyamato-quotes
